#!/bin/sh

# = = = = = = = = = = = = = = = = = = = = = = =
# =       Copyright (C) 2011 uib GmbH         =
# =           http://www.uib.de               =
# =          All rights reserved.             =
# = = = = = = = = = = = = = = = = = = = = = = =
  
/usr/bin/opsi-setup --set-rights $1
