#!/bin/sh

# = = = = = = = = = = = = = = = = = = = = = = =
# =     Copyright (C) 2011-2018 uib GmbH      =
# =           http://www.uib.de               =
# =          All rights reserved.             =
# = = = = = = = = = = = = = = = = = = = = = = =

/usr/bin/opsi-setup --set-rights $1
